### ISSUE TITLE
1.10.2 Starup Crash

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [BuiltBrokenModding/BBM-MFFS#35]
https://gist.github.com/P3rf3ctXZer0/3b360d12e0045ffcd702e5e19f8384b3

**Comment by DarkGuardsman** [comment]
Look at the crash I do not see anything relating to MFFS. I do however see a remark about IC2 not being found and the crash being inside of a mod called FoamFix

`Caused by: java.lang.ClassNotFoundException: ic2.api.tile.ExplosionWhitelist
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 46 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer pl.asie.foamfix.coremod.FoamFixTransformer@386f88b3 from coremod Do not report to Forge! Remove FoamFix (or replace with FoamFix-Lawful) and try again.
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:253)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)`
